project:
  type: website
  output-dir: docs

website:
  title: "Seth&Nut"
  site-url: "fralfaro.github.io/blog/"
  favicon: 'images/logo_sn.png'
  image: 'images/logo_sn.png'
  page-footer:
    left: "Website creado con [Quarto](https://quarto.org/) por Francisco Alfaro. Licencia: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/Seth-Nut
      - icon: linkedin
        href: https://www.linkedin.com/company/Seth-Nut/
      - icon: globe
        href: https://seth-nut.github.io/website/



  navbar:
    logo: /images/logo-kawai.png
    left:
      - text: Blog
        href: posts/index.qmd
      - text: Cursos
        href: teaching/index.qmd
      - text: Eventos
        href: talks/index.qmd
      - text: Nosotros
        menu:
          - text: Francisco Alfaro
            href: fran.qmd
          - text: Valeska Canales
            href: vale.qmd
          - text: Seth & Nut
            href: seth-nuth.qmd
    right:
      - icon: github
        href: https://github.com/Seth-Nut
      - icon: linkedin
        href: https://www.linkedin.com/company/Seth-Nut/
      - icon: globe
        href: https://seth-nut.github.io/website/

lang: es

format:
  html:
    smooth-scroll: true
    theme:
      - pulse
      - custom.scss
    link-external-icon: false
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true


editor: visual

comments:
  giscus:
    repo: Seth-Nut/resources

execute:
  freeze: true
